<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	class CardsDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO cards (
				nome_categoria
				, foto
				, link
				, cadastrado
				, modificado
				) VALUES";
				
		public $read = 
				"cards.id AS \"cards.id\"
				, cards.nome_categoria AS \"cards.nome_categoria\"
				, cards.foto AS \"cards.foto\"
				, cards.link AS \"cards.link\"
				, cards.cadastrado AS \"cards.cadastrado\"
				, cards.modificado AS \"cards.modificado\"
				";
				
		private $update = "UPDATE cards SET";
		private $delete = "DELETE FROM cards";
		
		public $from = "cards cards";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Cards}cards
		 */
		public function setCreate($cards) {		
			$this->sql = $this->create . " (\"" . 
					$cards->getNome_categoria() .
					"\", \"" . $cards->getFoto() .
					"\", \"" . $cards->getLink() .
					"\", \"" . $cards->getCadastrado() .
					"\", \"" . $cards->getModificado() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . " FROM " . $this->getFrom() . 
					$this->getWhere() . "
				" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Cards}cards  
		 * @param {String} where
		 */
		public function setUpdate($cards, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $cards->getId() . 
					"\", nome_categoria = \"" . $cards->getNome_categoria() . 
					"\", foto = \"" . $cards->getFoto() . 
					"\", link = \"" . $cards->getLink() . 
					"\", modificado = \"" . $cards->getModificado() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"cards.size\" from cards" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "cards.size", $row["cards.size"]);
				
				$pages = ceil($row["cards.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "cards.page", $this->connection->getPosition());
				$this->setResponse(0, "cards.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "cards.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Cards} cards 
		 * @return {Boolean}
		 */
		public function create($cards) {
			$result = "";

			$this->setCreate($cards);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "cards.id", $row["cards.id"]);
				$this->setResponse($line, "cards.nome_categoria", $row["cards.nome_categoria"]);
				$this->setResponse($line, "cards.nome_categoria.format.json", modelDoubleQuotesJson($row["cards.nome_categoria"]));
				$this->setResponse($line, "cards.nome_categoria.format", modelDoubleQuotes($row["cards.nome_categoria"]));
				$this->setResponse($line, "cards.nome_categoria.view", addLine($row["cards.nome_categoria"]));
				$this->setResponse($line, "cards.foto", $row["cards.foto"]);
				$this->setResponse($line, "cards.link", $row["cards.link"]);
				$this->setResponse($line, "cards.link.format.json", modelDoubleQuotesJson($row["cards.link"]));
				$this->setResponse($line, "cards.cadastrado", modelDateTime($row["cards.cadastrado"]));
				$this->setResponse($line, "cards.modificado", modelDateTime($row["cards.modificado"]));
			
				$this->setResponse($line, "cards.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Cards} cards 
		 * @return {Boolean}
		 */
		public function update($cards) {
			$result = "";
			
			$this->setUpdate($cards, "cards.id = " . $cards->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "cards.id", $row["cards.id"]);
				$this->setResponse($size, "cards.nome_categoria", $row["cards.nome_categoria"]);
			
				if ($row["cards.id"] == $selected)
					$this->setResponse($size, "cards.selected", "selected");
				else
					$this->setResponse($size, "cards.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "cards.id", $row["cards.id"]);
				$this->setResponse($size, "cards.nome_categoria", $row["cards.nome_categoria"]);
				$this->setResponse($size, "cards.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>