<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class CategoriasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO categorias (
				categoria
				, foto
				, cadastrado
				, modificado
				, cor
				) VALUES";
				
		public $read = 
				"categorias.id AS \"categorias.id\"
				, categorias.categoria AS \"categorias.categoria\"
				, categorias.foto AS \"categorias.foto\"
				, categorias.cadastrado AS \"categorias.cadastrado\"
				, categorias.modificado AS \"categorias.modificado\"
				, categorias.cor AS \"categorias.cor\"
				";
				
		private $update = "UPDATE categorias SET";
		private $delete = "DELETE FROM categorias";
		
		public $from = "categorias categorias";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Categorias}categorias
		 */
		public function setCreate($categorias) {		
			$this->sql = $this->create . " (\"" . 
					$categorias->getCategoria() .
					"\", \"" . $categorias->getFoto() .
					"\", \"" . $categorias->getCadastrado() .
					"\", \"" . $categorias->getModificado() .
					"\", \"" . $categorias->getCor() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$coresDao = new model\CoresDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $coresDao->read . 
					" FROM " . $this->getFrom() .", " . $coresDao->from . 
					($this->getWhere() == "" ? " WHERE categorias.cor = cores.id" : $this->getWhere()) . 
					" AND categorias.cor = cores.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Categorias}categorias  
		 * @param {String} where
		 */
		public function setUpdate($categorias, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $categorias->getId() . 
					"\", categoria = \"" . $categorias->getCategoria() . 
					"\", foto = \"" . $categorias->getFoto() . 
					"\", modificado = \"" . $categorias->getModificado() . 
					"\", cor = \"" . $categorias->getCor() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"categorias.size\" from categorias" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "categorias.size", $row["categorias.size"]);
				
				$pages = ceil($row["categorias.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "categorias.page", $this->connection->getPosition());
				$this->setResponse(0, "categorias.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "categorias.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Categorias} categorias 
		 * @return {Boolean}
		 */
		public function create($categorias) {
			$result = "";

			$this->setCreate($categorias);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "categorias.id", $row["categorias.id"]);
				$this->setResponse($line, "categorias.categoria", $row["categorias.categoria"]);
				$this->setResponse($line, "categorias.categoria.format.json", modelDoubleQuotesJson($row["categorias.categoria"]));
				$this->setResponse($line, "categorias.categoria.format", modelDoubleQuotes($row["categorias.categoria"]));
				$this->setResponse($line, "categorias.categoria.view", addLine($row["categorias.categoria"]));
				$this->setResponse($line, "categorias.foto", $row["categorias.foto"]);
				$this->setResponse($line, "categorias.cadastrado", modelDateTime($row["categorias.cadastrado"]));
				$this->setResponse($line, "categorias.modificado", modelDateTime($row["categorias.modificado"]));
				$this->setResponse($line, "categorias.cor", $row["categorias.cor"]);
				$this->setResponse($line, "cores.cor", $row["cores.cor"]);
			
				$this->setResponse($line, "categorias.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Categorias} categorias 
		 * @return {Boolean}
		 */
		public function update($categorias) {
			$result = "";
			
			$this->setUpdate($categorias, "categorias.id = " . $categorias->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "categorias.id", $row["categorias.id"]);
				$this->setResponse($size, "categorias.categoria", $row["categorias.categoria"]);
			
				if ($row["categorias.id"] == $selected)
					$this->setResponse($size, "categorias.selected", "selected");
				else
					$this->setResponse($size, "categorias.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "categorias.id", $row["categorias.id"]);
				$this->setResponse($size, "categorias.categoria", $row["categorias.categoria"]);
				$this->setResponse($size, "categorias.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>