<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Categorias {
			
		private $id;
		private $categoria;
		private $foto;
		private $cadastrado;
		private $modificado;
		private $cor;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setCategoria($categoria) {
			$this->categoria = $categoria;
		}
		
		public function getCategoria() {
			return $this->categoria;
		}
					
		public function setFoto($foto) {
			$this->foto = $foto;
		}
		
		public function getFoto() {
			return $this->foto;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setCor($cor) {
			$this->cor = $cor;
		}
		
		public function getCor() {
			return $this->cor;
		}
					
	}
	
?>