<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	class CoresDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO cores (
				cor
				, hexadecimal
				, cadastrado
				, modificado
				) VALUES";
				
		public $read = 
				"cores.id AS \"cores.id\"
				, cores.cor AS \"cores.cor\"
				, cores.hexadecimal AS \"cores.hexadecimal\"
				, cores.cadastrado AS \"cores.cadastrado\"
				, cores.modificado AS \"cores.modificado\"
				";
				
		private $update = "UPDATE cores SET";
		private $delete = "DELETE FROM cores";
		
		public $from = "cores cores";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Cores}cores
		 */
		public function setCreate($cores) {		
			$this->sql = $this->create . " (\"" . 
					$cores->getCor() .
					"\", \"" . $cores->getHexadecimal() .
					"\", \"" . $cores->getCadastrado() .
					"\", \"" . $cores->getModificado() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . " FROM " . $this->getFrom() . 
					$this->getWhere() . "
				" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Cores}cores  
		 * @param {String} where
		 */
		public function setUpdate($cores, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $cores->getId() . 
					"\", cor = \"" . $cores->getCor() . 
					"\", hexadecimal = \"" . $cores->getHexadecimal() . 
					"\", modificado = \"" . $cores->getModificado() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"cores.size\" from cores" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "cores.size", $row["cores.size"]);
				
				$pages = ceil($row["cores.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "cores.page", $this->connection->getPosition());
				$this->setResponse(0, "cores.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "cores.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Cores} cores 
		 * @return {Boolean}
		 */
		public function create($cores) {
			$result = "";

			$this->setCreate($cores);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "cores.id", $row["cores.id"]);
				$this->setResponse($line, "cores.cor", $row["cores.cor"]);
				$this->setResponse($line, "cores.cor.format.json", modelDoubleQuotesJson($row["cores.cor"]));
				$this->setResponse($line, "cores.cor.format", modelDoubleQuotes($row["cores.cor"]));
				$this->setResponse($line, "cores.cor.view", addLine($row["cores.cor"]));
				$this->setResponse($line, "cores.hexadecimal", $row["cores.hexadecimal"]);
				$this->setResponse($line, "cores.hexadecimal.format.json", modelDoubleQuotesJson($row["cores.hexadecimal"]));
				$this->setResponse($line, "cores.cadastrado", modelDateTime($row["cores.cadastrado"]));
				$this->setResponse($line, "cores.modificado", modelDateTime($row["cores.modificado"]));
			
				$this->setResponse($line, "cores.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Cores} cores 
		 * @return {Boolean}
		 */
		public function update($cores) {
			$result = "";
			
			$this->setUpdate($cores, "cores.id = " . $cores->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "cores.id", $row["cores.id"]);
				$this->setResponse($size, "cores.cor", $row["cores.cor"]);
			
				if ($row["cores.id"] == $selected)
					$this->setResponse($size, "cores.selected", "selected");
				else
					$this->setResponse($size, "cores.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "cores.id", $row["cores.id"]);
				$this->setResponse($size, "cores.cor", $row["cores.cor"]);
				$this->setResponse($size, "cores.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>