<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class EstabelecimentosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO estabelecimentos (
				estabelecimento
				, cnpj
				, telefone
				, celular
				, celular2
				, email
				, cadastrado
				, modificado
				, endereco
				) VALUES";
				
		public $read = 
				"estabelecimentos.id AS \"estabelecimentos.id\"
				, estabelecimentos.estabelecimento AS \"estabelecimentos.estabelecimento\"
				, estabelecimentos.cnpj AS \"estabelecimentos.cnpj\"
				, estabelecimentos.telefone AS \"estabelecimentos.telefone\"
				, estabelecimentos.celular AS \"estabelecimentos.celular\"
				, estabelecimentos.celular2 AS \"estabelecimentos.celular2\"
				, estabelecimentos.email AS \"estabelecimentos.email\"
				, estabelecimentos.cadastrado AS \"estabelecimentos.cadastrado\"
				, estabelecimentos.modificado AS \"estabelecimentos.modificado\"
				, estabelecimentos.endereco AS \"estabelecimentos.endereco\"
				";
				
		private $update = "UPDATE estabelecimentos SET";
		private $delete = "DELETE FROM estabelecimentos";
		
		public $from = "estabelecimentos estabelecimentos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Estabelecimentos}estabelecimentos
		 */
		public function setCreate($estabelecimentos) {		
			$this->sql = $this->create . " (\"" . 
					$estabelecimentos->getEstabelecimento() .
					"\", \"" . $estabelecimentos->getCnpj() .
					"\", \"" . $estabelecimentos->getTelefone() .
					"\", \"" . $estabelecimentos->getCelular() .
					"\", \"" . $estabelecimentos->getCelular2() .
					"\", \"" . $estabelecimentos->getEmail() .
					"\", \"" . $estabelecimentos->getCadastrado() .
					"\", \"" . $estabelecimentos->getModificado() .
					"\", \"" . $estabelecimentos->getEndereco() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$enderecosDao = new model\EnderecosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $enderecosDao->read . 
					" FROM " . $this->getFrom() .", " . $enderecosDao->from . 
					($this->getWhere() == "" ? " WHERE estabelecimentos.endereco = enderecos.id" : $this->getWhere()) . 
					" AND estabelecimentos.endereco = enderecos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Estabelecimentos}estabelecimentos  
		 * @param {String} where
		 */
		public function setUpdate($estabelecimentos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $estabelecimentos->getId() . 
					"\", estabelecimento = \"" . $estabelecimentos->getEstabelecimento() . 
					"\", cnpj = \"" . $estabelecimentos->getCnpj() . 
					"\", telefone = \"" . $estabelecimentos->getTelefone() . 
					"\", celular = \"" . $estabelecimentos->getCelular() . 
					"\", celular2 = \"" . $estabelecimentos->getCelular2() . 
					"\", email = \"" . $estabelecimentos->getEmail() . 
					"\", modificado = \"" . $estabelecimentos->getModificado() . 
					"\", endereco = \"" . $estabelecimentos->getEndereco() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"estabelecimentos.size\" from estabelecimentos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "estabelecimentos.size", $row["estabelecimentos.size"]);
				
				$pages = ceil($row["estabelecimentos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "estabelecimentos.page", $this->connection->getPosition());
				$this->setResponse(0, "estabelecimentos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "estabelecimentos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Estabelecimentos} estabelecimentos 
		 * @return {Boolean}
		 */
		public function create($estabelecimentos) {
			$result = "";

			$this->setCreate($estabelecimentos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "estabelecimentos.id", $row["estabelecimentos.id"]);
				$this->setResponse($line, "estabelecimentos.estabelecimento", $row["estabelecimentos.estabelecimento"]);
				$this->setResponse($line, "estabelecimentos.estabelecimento.format.json", modelDoubleQuotesJson($row["estabelecimentos.estabelecimento"]));
				$this->setResponse($line, "estabelecimentos.estabelecimento.format", modelDoubleQuotes($row["estabelecimentos.estabelecimento"]));
				$this->setResponse($line, "estabelecimentos.estabelecimento.view", addLine($row["estabelecimentos.estabelecimento"]));
				$this->setResponse($line, "estabelecimentos.cnpj", $row["estabelecimentos.cnpj"]);
				$this->setResponse($line, "estabelecimentos.telefone", $row["estabelecimentos.telefone"]);
				$this->setResponse($line, "estabelecimentos.celular", $row["estabelecimentos.celular"]);
				$this->setResponse($line, "estabelecimentos.celular2", $row["estabelecimentos.celular2"]);
				$this->setResponse($line, "estabelecimentos.celular2.format.json", modelDoubleQuotesJson($row["estabelecimentos.celular2"]));
				$this->setResponse($line, "estabelecimentos.email", $row["estabelecimentos.email"]);
				$this->setResponse($line, "estabelecimentos.cadastrado", modelDateTime($row["estabelecimentos.cadastrado"]));
				$this->setResponse($line, "estabelecimentos.modificado", modelDateTime($row["estabelecimentos.modificado"]));
				$this->setResponse($line, "estabelecimentos.endereco", $row["estabelecimentos.endereco"]);
				$this->setResponse($line, "enderecos.endereco", $row["enderecos.endereco"]);
			
				$this->setResponse($line, "estabelecimentos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Estabelecimentos} estabelecimentos 
		 * @return {Boolean}
		 */
		public function update($estabelecimentos) {
			$result = "";
			
			$this->setUpdate($estabelecimentos, "estabelecimentos.id = " . $estabelecimentos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimentos.id", $row["estabelecimentos.id"]);
				$this->setResponse($size, "estabelecimentos.estabelecimento", $row["estabelecimentos.estabelecimento"]);
			
				if ($row["estabelecimentos.id"] == $selected)
					$this->setResponse($size, "estabelecimentos.selected", "selected");
				else
					$this->setResponse($size, "estabelecimentos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimentos.id", $row["estabelecimentos.id"]);
				$this->setResponse($size, "estabelecimentos.estabelecimento", $row["estabelecimentos.estabelecimento"]);
				$this->setResponse($size, "estabelecimentos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>