<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Estabelecimentos {
			
		private $id;
		private $estabelecimento;
		private $cnpj;
		private $telefone;
		private $celular;
		private $celular2;
		private $email;
		private $cadastrado;
		private $modificado;
		private $endereco;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setEstabelecimento($estabelecimento) {
			$this->estabelecimento = $estabelecimento;
		}
		
		public function getEstabelecimento() {
			return $this->estabelecimento;
		}
					
		public function setCnpj($cnpj) {
			$this->cnpj = $cnpj;
		}
		
		public function getCnpj() {
			return $this->cnpj;
		}
					
		public function setTelefone($telefone) {
			$this->telefone = $telefone;
		}
		
		public function getTelefone() {
			return $this->telefone;
		}
					
		public function setCelular($celular) {
			$this->celular = $celular;
		}
		
		public function getCelular() {
			return $this->celular;
		}
					
		public function setCelular2($celular2) {
			$this->celular2 = $celular2;
		}
		
		public function getCelular2() {
			return $this->celular2;
		}
					
		public function setEmail($email) {
			$this->email = $email;
		}
		
		public function getEmail() {
			return $this->email;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setEndereco($endereco) {
			$this->endereco = $endereco;
		}
		
		public function getEndereco() {
			return $this->endereco;
		}
					
	}
	
?>