<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Produto_precos {
			
		private $id;
		private $produto_preco;
		private $cadastrado;
		private $modificado;
		private $produto;
		private $estabelecimento;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setProduto_preco($produto_preco) {
			$this->produto_preco = $produto_preco;
		}
		
		public function getProduto_preco() {
			return $this->produto_preco;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setProduto($produto) {
			$this->produto = $produto;
		}
		
		public function getProduto() {
			return $this->produto;
		}
					
		public function setEstabelecimento($estabelecimento) {
			$this->estabelecimento = $estabelecimento;
		}
		
		public function getEstabelecimento() {
			return $this->estabelecimento;
		}
					
	}
	
?>