<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class ProdutosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO produtos (
				produto
				, cadastrado
				, modificado
				, categoria
				, marca
				) VALUES";
				
		public $read = 
				"produtos.id AS \"produtos.id\"
				, produtos.produto AS \"produtos.produto\"
				, produtos.cadastrado AS \"produtos.cadastrado\"
				, produtos.modificado AS \"produtos.modificado\"
				, produtos.categoria AS \"produtos.categoria\"
				, produtos.marca AS \"produtos.marca\"
				";
				
		private $update = "UPDATE produtos SET";
		private $delete = "DELETE FROM produtos";
		
		public $from = "produtos produtos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Produtos}produtos
		 */
		public function setCreate($produtos) {		
			$this->sql = $this->create . " (\"" . 
					$produtos->getProduto() .
					"\", \"" . $produtos->getCadastrado() .
					"\", \"" . $produtos->getModificado() .
					"\", \"" . $produtos->getCategoria() .
					"\", \"" . $produtos->getMarca() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$categoriasDao = new model\CategoriasDao($this->connection);
			$marcasDao = new model\MarcasDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $categoriasDao->read . ", " . $marcasDao->read . 
					" FROM " . $this->getFrom() .", " . $categoriasDao->from . ", " . $marcasDao->from . 
					($this->getWhere() == "" ? " WHERE produtos.categoria = categorias.id AND produtos.marca = marcas.id" : $this->getWhere()) . 
					" AND produtos.categoria = categorias.id AND produtos.marca = marcas.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Produtos}produtos  
		 * @param {String} where
		 */
		public function setUpdate($produtos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $produtos->getId() . 
					"\", produto = \"" . $produtos->getProduto() . 
					"\", modificado = \"" . $produtos->getModificado() . 
					"\", categoria = \"" . $produtos->getCategoria() . 
					"\", marca = \"" . $produtos->getMarca() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"produtos.size\" from produtos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "produtos.size", $row["produtos.size"]);
				
				$pages = ceil($row["produtos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "produtos.page", $this->connection->getPosition());
				$this->setResponse(0, "produtos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "produtos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Produtos} produtos 
		 * @return {Boolean}
		 */
		public function create($produtos) {
			$result = "";

			$this->setCreate($produtos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "produtos.id", $row["produtos.id"]);
				$this->setResponse($line, "produtos.produto", $row["produtos.produto"]);
				$this->setResponse($line, "produtos.produto.format.json", modelDoubleQuotesJson($row["produtos.produto"]));
				$this->setResponse($line, "produtos.produto.format", modelDoubleQuotes($row["produtos.produto"]));
				$this->setResponse($line, "produtos.produto.view", addLine($row["produtos.produto"]));
				$this->setResponse($line, "produtos.cadastrado", modelDateTime($row["produtos.cadastrado"]));
				$this->setResponse($line, "produtos.modificado", modelDateTime($row["produtos.modificado"]));
				$this->setResponse($line, "produtos.categoria", $row["produtos.categoria"]);
				$this->setResponse($line, "categorias.categoria", $row["categorias.categoria"]);
				$this->setResponse($line, "produtos.marca", $row["produtos.marca"]);
				$this->setResponse($line, "marcas.marca", $row["marcas.marca"]);
			
				$this->setResponse($line, "produtos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Produtos} produtos 
		 * @return {Boolean}
		 */
		public function update($produtos) {
			$result = "";
			
			$this->setUpdate($produtos, "produtos.id = " . $produtos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "produtos.id", $row["produtos.id"]);
				$this->setResponse($size, "produtos.produto", $row["produtos.produto"]);
			
				if ($row["produtos.id"] == $selected)
					$this->setResponse($size, "produtos.selected", "selected");
				else
					$this->setResponse($size, "produtos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "produtos.id", $row["produtos.id"]);
				$this->setResponse($size, "produtos.produto", $row["produtos.produto"]);
				$this->setResponse($size, "produtos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>