<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Produto_precosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO produto_precos (
				produto_preco
				, cadastrado
				, modificado
				, produto
				, estabelecimento
				) VALUES";
				
		public $read = 
				"produto_precos.id AS \"produto_precos.id\"
				, produto_precos.produto_preco AS \"produto_precos.produto_preco\"
				, produto_precos.cadastrado AS \"produto_precos.cadastrado\"
				, produto_precos.modificado AS \"produto_precos.modificado\"
				, produto_precos.produto AS \"produto_precos.produto\"
				, produto_precos.estabelecimento AS \"produto_precos.estabelecimento\"
				";
				
		private $update = "UPDATE produto_precos SET";
		private $delete = "DELETE FROM produto_precos";
		
		public $from = "produto_precos produto_precos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Produto_precos}produto_precos
		 */
		public function setCreate($produto_precos) {		
			$this->sql = $this->create . " (\"" . 
					$produto_precos->getProduto_preco() .
					"\", \"" . $produto_precos->getCadastrado() .
					"\", \"" . $produto_precos->getModificado() .
					"\", \"" . $produto_precos->getProduto() .
					"\", \"" . $produto_precos->getEstabelecimento() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$produtosDao = new model\ProdutosDao($this->connection);
			$estabelecimentosDao = new model\EstabelecimentosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $produtosDao->read . ", " . $estabelecimentosDao->read . 
					" FROM " . $this->getFrom() .", " . $produtosDao->from . ", " . $estabelecimentosDao->from . 
					($this->getWhere() == "" ? " WHERE produto_precos.produto = produtos.id AND produto_precos.estabelecimento = estabelecimentos.id" : $this->getWhere()) . 
					" AND produto_precos.produto = produtos.id AND produto_precos.estabelecimento = estabelecimentos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Produto_precos}produto_precos  
		 * @param {String} where
		 */
		public function setUpdate($produto_precos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $produto_precos->getId() . 
					"\", produto_preco = \"" . $produto_precos->getProduto_preco() . 
					"\", modificado = \"" . $produto_precos->getModificado() . 
					"\", produto = \"" . $produto_precos->getProduto() . 
					"\", estabelecimento = \"" . $produto_precos->getEstabelecimento() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"produto_precos.size\" from produto_precos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "produto_precos.size", $row["produto_precos.size"]);
				
				$pages = ceil($row["produto_precos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "produto_precos.page", $this->connection->getPosition());
				$this->setResponse(0, "produto_precos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "produto_precos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Produto_precos} produto_precos 
		 * @return {Boolean}
		 */
		public function create($produto_precos) {
			$result = "";

			$this->setCreate($produto_precos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "produto_precos.id", $row["produto_precos.id"]);
				$this->setResponse($line, "produto_precos.produto_preco", modelDouble($row["produto_precos.produto_preco"]));
				$this->setResponse($line, "produto_precos.cadastrado", modelDateTime($row["produto_precos.cadastrado"]));
				$this->setResponse($line, "produto_precos.modificado", modelDateTime($row["produto_precos.modificado"]));
				$this->setResponse($line, "produto_precos.produto", $row["produto_precos.produto"]);
				$this->setResponse($line, "produtos.produto", $row["produtos.produto"]);
				$this->setResponse($line, "produto_precos.estabelecimento", $row["produto_precos.estabelecimento"]);
				$this->setResponse($line, "estabelecimentos.estabelecimento", $row["estabelecimentos.estabelecimento"]);
			
				$this->setResponse($line, "produto_precos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Produto_precos} produto_precos 
		 * @return {Boolean}
		 */
		public function update($produto_precos) {
			$result = "";
			
			$this->setUpdate($produto_precos, "produto_precos.id = " . $produto_precos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "produto_precos.id", $row["produto_precos.id"]);
				$this->setResponse($size, "produto_precos.produto_preco", $row["produto_precos.produto_preco"]);
			
				if ($row["produto_precos.id"] == $selected)
					$this->setResponse($size, "produto_precos.selected", "selected");
				else
					$this->setResponse($size, "produto_precos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "produto_precos.id", $row["produto_precos.id"]);
				$this->setResponse($size, "produto_precos.produto_preco", $row["produto_precos.produto_preco"]);
				$this->setResponse($size, "produto_precos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>