<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	 
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	if ($method == "page") {
		$token = base64_decode($_COOKIE[$_PROJECT]);
		$tokenMath = explode("g3tz", $token);
		$id = ($tokenMath[1] / 128) - 32;
		$daoFactory->beginTransaction();
		$response["usuarios"] = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $id . 
				" AND usuarios.situacao_registro = 1", "usuarios.id ASC", true);
		$daoFactory->close();
		if (is_array($response["usuarios"]) && sizeof($response["usuarios"]) > 0) {
			$view->setTitle(ucfirst($screen));
			$view->setDescription("");
			$view->setKeywords("");
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/inicio.html", $response);
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
		} else {
			header("Location: " . $view->getRoot() . "/home");
		}
	}

?>