<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "produtos.produto LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "produtos.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "produtos.produto = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
		
	if ($order != "") {
		$o = explode("<gz>", $order);

		$limit = $o[0] . " " . $o[1] . " LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
				
	} else {
		if ($position > 0 && $itensPerPage > 0) {
			$limit = "produtos.id DESC LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["produtos"] = $daoFactory->getProdutosDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["produtos"][0]["produtos.produto"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/@_PAGE.html" : "/html/produtos.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$produtos = new model\Produtos();
			$produtos->setProduto(logicNull($request["produtos.produto"]));
			$produtos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$produtos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$produtos->setCategoria($request["produtos.categoria"]);
			$produtos->setMarca($request["produtos.marca"]);
			
			$resultDao = $daoFactory->getProdutosDao()->create($produtos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "produtos.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$produtos = $daoFactory->getProdutosDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($produtos);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$produtos = new model\Produtos();
			$produtos->setId($request["produtos.id"]);
			$produtos->setProduto(logicNull($request["produtos.produto"]));
			$produtos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$produtos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$produtos->setCategoria($request["produtos.categoria"]);
			$produtos->setMarca($request["produtos.marca"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getProdutosDao()->update($produtos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["produtos.id"] = $daoFactory->prepare($request["produtos.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["produtos.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "produtos.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getProdutosDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["categorias"] = $daoFactory->getCategoriasDao()->read("", "categorias.id ASC", false);
					$response["marcas"] = $daoFactory->getMarcasDao()->read("", "marcas.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["produtos"] = $daoFactory->getProdutosDao()->read($where, $limit, true);
					if (!is_array($response["produtos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["produtos"] = $daoFactory->getProdutosDao()->read($where, "", true);
					$response["produtos"][0]["produtos.categorias"] = $daoFactory->getCategoriasDao()->read("", "categorias.id ASC", false);
					for ($x = 0; $x < sizeof($response["produtos"][0]["produtos.categorias"]); $x++) {
						if ($response["produtos"][0]["produtos.categorias"][$x]["categorias.id"] == 
								$response["produtos"][0]["produtos.categoria"]) {
							$response["produtos"][0]["produtos.categorias"][$x]["categorias.selected"] = "selected";
						}
					}
					$response["produtos"][0]["produtos.marcas"] = $daoFactory->getMarcasDao()->read("", "marcas.id ASC", false);
					for ($x = 0; $x < sizeof($response["produtos"][0]["produtos.marcas"]); $x++) {
						if ($response["produtos"][0]["produtos.marcas"][$x]["marcas.id"] == 
								$response["produtos"][0]["produtos.marca"]) {
							$response["produtos"][0]["produtos.marcas"][$x]["marcas.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND produtos.@_FOREIGN_KEY = " . $base;
					else 
						$where = "produtos.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["produtos"] = $daoFactory->getProdutosDao()->read($where, $limit, true);
					if (!is_array($response["produtos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND produtos.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "produtos.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "produtos.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["produtos"] = $daoFactory->getProdutosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosSCR.html", $response) . 
						"<size>" . (is_array($response["produtos"]) ? $response["produtos"][0]["produtos.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "produtos.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["produtos"] = $daoFactory->getProdutosDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/produtos/produtosCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$produtos = new model\Produtos();
					$produtos->setProduto(logicNull($form[0]));
					$produtos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$produtos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$produtos->setCategoria($form[1]);
					$produtos->setMarca($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getProdutosDao()->create($produtos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$produtos = new model\Produtos();
					$produtos->setId($code);
					$produtos->setProduto(logicNull($form[0]));
					$produtos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$produtos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$produtos->setCategoria($form[1]);
					$produtos->setMarca($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getProdutosDao()->update($produtos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "produtos.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getProdutosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>